name: Gemini Document Translation

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **.md
          files_ignore: |
            **.ja.md
            **.zh-TW.md
            **.zh-CN.md

      - name: Run Gemini translation
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: google-github-actions/run-gemini-cli@v0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            Translate changed markdown files in this PR to Japanese, Traditional Chinese, and Simplified Chinese.
            Changed files: ${{ steps.changed-files.outputs.all_changed_files }}
            Post translations as a comment. Do not create files.
